name: CI

on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  CI:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }}

      - name: Install Node.js dependencies
        run: npm ci

      - name: Prettify code
        uses: creyD/prettier_action@v3.3
        with:
          prettier_options: --write **/*.{js,ts,md}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Eslint
        run: npm run lint
        env:
          CI: true

      - name: Unit tests
        run: npm run test
        env:
          CI: true
