name: CI

on:
  release:
    types: [published]

  workflow_dispatch:

jobs:
  CI:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node v18.12.1
        uses: actions/setup-node@v3
        with:
          node-version: 18.12.1
          registry-url: 'https://registry.npmjs.org'

      - name: Install Node.js dependencies
        run: npm install --force --legacy-peer-deps

      - name: Building
        run: npm run build
        env:
          CI: true

      - name: Getting version
        id: versions-variables
        run: |
          echo ::set-output name=VERSION_NAME::${GITHUB_REF#refs/*/}
          echo ::set-output name=VERSION_NUMBER::$(echo $GITHUB_REF | cut -d / -f 3 | awk '{sub(/v/,"")}1')

      - name: Check output version
        env:
          RELEASE_VERSION: ${{ steps.versions-variables.outputs.VERSION_NAME }}
        run: |
          echo $RELEASE_VERSION
          echo ${{ steps.versions-variables.outputs.VERSION_NUMBER }}

      - name: Setup package version
        run: npm version ${{ steps.versions-variables.outputs.VERSION_NUMBER }} --no-git-tag-version --force

      - name: Publishing package
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
